// @ts-nocheck -- skip type checking
import * as docs_doc_4 from "../content/docs/(introductions)/audio-and-output-settings.mdx?collection=docs&hash=f9b1d2293ac5ad5a68ace4f1cd8054c9"
import * as docs_doc_3 from "../content/docs/purpose-of-the-software.mdx?collection=docs&hash=f9b1d2293ac5ad5a68ace4f1cd8054c9"
import * as docs_doc_2 from "../content/docs/key-features.mdx?collection=docs&hash=f9b1d2293ac5ad5a68ace4f1cd8054c9"
import * as docs_doc_1 from "../content/docs/index.mdx?collection=docs&hash=f9b1d2293ac5ad5a68ace4f1cd8054c9"
import * as docs_doc_0 from "../content/docs/audio-and-output-settings.mdx?collection=docs&hash=f9b1d2293ac5ad5a68ace4f1cd8054c9"
import * as blogPosts_doc_2 from "../content/blog/Mastering-Techniques-in-FL-Studio.mdx?collection=blogPosts&hash=f9b1d2293ac5ad5a68ace4f1cd8054c9"
import * as blogPosts_doc_1 from "../content/blog/Hardware-vs-Software-Synths-The-Ultimate-Comparison.mdx?collection=blogPosts&hash=f9b1d2293ac5ad5a68ace4f1cd8054c9"
import * as blogPosts_doc_0 from "../content/blog/10-Best-Free-VST-Plugins-of-2024.mdx?collection=blogPosts&hash=f9b1d2293ac5ad5a68ace4f1cd8054c9"
import { _runtime } from "fumadocs-mdx"
import * as _source from "../source.config"
export const blogPosts = _runtime.doc<typeof _source.blogPosts>([{ info: {"path":"10-Best-Free-VST-Plugins-of-2024.mdx","absolutePath":"/home/devplus2025/Documents/Project/mus-motion/content/blog/10-Best-Free-VST-Plugins-of-2024.mdx"}, data: blogPosts_doc_0 }, { info: {"path":"Hardware-vs-Software-Synths-The-Ultimate-Comparison.mdx","absolutePath":"/home/devplus2025/Documents/Project/mus-motion/content/blog/Hardware-vs-Software-Synths-The-Ultimate-Comparison.mdx"}, data: blogPosts_doc_1 }, { info: {"path":"Mastering-Techniques-in-FL-Studio.mdx","absolutePath":"/home/devplus2025/Documents/Project/mus-motion/content/blog/Mastering-Techniques-in-FL-Studio.mdx"}, data: blogPosts_doc_2 }]);
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"audio-and-output-settings.mdx","absolutePath":"/home/devplus2025/Documents/Project/mus-motion/content/docs/audio-and-output-settings.mdx"}, data: docs_doc_0 }, { info: {"path":"index.mdx","absolutePath":"/home/devplus2025/Documents/Project/mus-motion/content/docs/index.mdx"}, data: docs_doc_1 }, { info: {"path":"key-features.mdx","absolutePath":"/home/devplus2025/Documents/Project/mus-motion/content/docs/key-features.mdx"}, data: docs_doc_2 }, { info: {"path":"purpose-of-the-software.mdx","absolutePath":"/home/devplus2025/Documents/Project/mus-motion/content/docs/purpose-of-the-software.mdx"}, data: docs_doc_3 }, { info: {"path":"(introductions)/audio-and-output-settings.mdx","absolutePath":"/home/devplus2025/Documents/Project/mus-motion/content/docs/(introductions)/audio-and-output-settings.mdx"}, data: docs_doc_4 }], [])